### PR TITLE
Update dependencies, use latest lens

### PR DESCRIPTION
**Pull request by garyb**
This should work once joneshf/purescript-optic#2 is merged and a new release is made.

### CODE REVIEW

**Comment by jdegoes** [comment]
Awesome, will wait for @joneshf to accept the PR and issue new version of Optic.

**Comment by jdegoes** [comment]
Someone Argonaut broke due to the profunctor issue (I think). :-/

**Comment by joneshf** [comment]
Ah, looks like it's trying to download a version of the compiler that doesn't exist. If someone doesn't get to it by tomorrow, I'll update it.

**Comment by garyb** [comment]
There we go. Odd that that's an error now, I would have thought the old tag would still be usable if it worked at one point.

**Comment by joneshf** [comment]
The releases before `0.6.2` were removed because they lacked the License file. They'd have to be added back manually, but I'm not sure it's worth the trouble.

In any case, thanks!

**Pull request merged**
