### PR TITLE
Resolves issue #13

### PR DESCRIPTION
**Pull request by ethul**
The generated JS for decodeJsonMaybe was recursively calling itself.
This applies the Just constructor in the case the value within the Maybe
successfully decodes to resolve the issue.

### CODE REVIEW

**Comment by jdegoes** [comment]
The build is failing because of Math.random. Can you upgrade the version of the compiler used in Travis?

**Comment by jdegoes** [comment]
By the way, thanks for this PR, it's most welcome!

**Comment by paf31** [comment]
I haven't released the version with the fix yet. Will do today hopefully.

**Comment by ethul** [comment]
Welcome on the PR. I can update travis once we have a release. Thanks for the update @paf31

**Comment by ethul** [comment]
Ah, just noticed there is not yet a linux64 binary for 0.6.7. This is causing the new travis failure.

**Comment by paf31** [comment]
Yes, for some reason the CI build broke during the upload. I'll try to restart it.

**Comment by ethul** [comment]
Thanks @paf31

**Comment by paf31** [comment]
Ok, it worked this time. Maybe restart your CI build?

**Comment by ethul** [comment]
Can someone with write access to this repo please restart the CI build? I don't have the necessary permissions.

**Comment by joneshf** [comment]
Just restarted it.

**Comment by ethul** [comment]
Great, thanks!

**Comment by jdegoes** [comment]
@ethul Sorry for the delay on this, can you resolve conflicts here?

**Comment by ethul** [comment]
@jdegoes No worries. I will resolve the conflicts.

**Comment by ethul** [comment]
@jdegoes conflicts resolved

**Pull request merged**
