### PR TITLE
Bump dependency versions

### PR DESCRIPTION
**Pull request by davezuch**
## What does this pull request do?

Bumps dependency versions of bundled libs.

## Other Notes:

Should this lib even be maintained? Seems like so much extra work to keep all the packages in sync, but I think as long as it's published it should be kept up to date. Or somehow deprecated.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Thanks @davezuch! 

I agree there's extra work in maintaining this package and keeping these versions together. 

- You can achieve the same result by installing the three Argonaut libraries directly, or by only installing the ones you are using. 
- Sometimes the three latest versions aren't compatible with other libraries, like when `argonaut-traversals` was not compatible with Halogen 4 but `argonaut-core` and `argonaut-codecs` were
- Sometimes this library falls behind, so installing `argonaut` doesn't get you the latest versions of its constituent packages
- Arguably the idea of letting you install all the Argonaut stuff with versions that work together could be equally well solved by just using a package set, though those are still not standard in PS yet

As far as arguments for keeping the package as-is, it's much friendlier to just install Argonaut rather than have to search for the three packages that make it up and install them separately. I'm not even sure the packages have obvious links to one another outside this one. A beginner would certainly have trouble figuring out what is meant to be installed with what.

Since the packages are already separate, I think it's worth keeping this one around just so people can install a single thing to get all Argonaut library code at once. We could also improve the readme by giving better descriptions of the constituent libraries and making a note that you can simply install the ones you need (typically core + codecs) directly if this one is out of sync with the versions you want.

**Comment by bosyi** [comment]
@thomashoneyman you write a lot of text but I did not understand, are you going to merge this?

**Comment by thomashoneyman** [comment]
@bosyi Sorry -- yes, though I'd like to revisit that conversation in the future.

**Comment by thomashoneyman** [comment]
See: https://github.com/purescript-contrib/purescript-argonaut/releases/tag/v6.0.0

**Pull request merged**
